//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_MAL_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        public int characterId { get; set; }
        public Nullable<int> mangaId { get; set; }
        public string name { get; set; }
        public string lastname { get; set; }
        public string appearance { get; set; }
        public int age { get; set; }
        public string bloodtype { get; set; }
        public string height { get; set; }
    
        public virtual Manga Manga { get; set; }
    }
}
